version: '2'
services:
  wowza:
    build:
      context: .
    image: flexconstructor/wowza-webrtc
    container_name: wowza
    environment:
      - WSE_LIC=ET1E4-nMFp4-46zDu-6Kv7M-DnyAp-xvyz3-6TdnZNGXhyTY
    ports:
      - "1935:1935"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "443:8443"
      - "9443:9443"
    volumes:
      - ./logs/engine:/usr/local/WowzaStreamingEngine/logs
      - ./logs/manager:/usr/local/WowzaStreamingEngine/manager/logs
      - ./logs/supervisord:/supervisor/supervisord.log
    entrypoint: /sbin/entrypoint.sh
